import {createAction} from 'redux-actions';

export default {
  "RECIPES/FETCH_RECIPES": createAction("RECIPES/FETCH_RECIPES"),
  "RECIPES/FETCH_RECIPES_SUCCESSFULLY": createAction("RECIPES/FETCH_RECIPES_SUCCESSFULLY"),
  "RECIPES/FETCH_RECIPES_ERROR": createAction("RECIPES/FETCH_RECIPES_ERROR"),

  "RECIPES/RECIPE_REMOVE": createAction("RECIPES/RECIPE_REMOVE"),
  "RECIPES/RECIPE_REMOVE_SUCCESSFULLY": createAction("RECIPES/RECIPE_REMOVE_SUCCESSFULLY"),
  "RECIPES/RECIPE_REMOVE_ERROR": createAction("RECIPES/RECIPE_REMOVE_ERROR"),

  "RECIPES/ALL_REMOVE": createAction("RECIPES/ALL_REMOVE"),
  "RECIPES/ALL_REMOVE_SUCCESSFULLY": createAction("RECIPES/ALL_REMOVE_SUCCESSFULLY"),
  "RECIPES/ALL_REMOVE_ERROR": createAction("RECIPES/ALL_REMOVE_ERROR"),

  "RECIPES/ADDED_NEW_RECIPE": createAction("RECIPES/ADDED_NEW_RECIPE"),
  "RECIPES/ADDED_NEW_RECIPE_SUCCESSFULLY": createAction("RECIPES/ADDED_NEW_RECIPE_SUCCESSFULLY"),
  "RECIPES/ADDED_NEW_RECIPE_ERROR": createAction("RECIPES/ADDED_NEW_RECIPE_ERROR"),

  "RECIPES/CLOSE_EDIT_FORM": createAction("RECIPES/CLOSE_EDIT_FORM"),
  "RECIPES/OPEN_EDIT_FORM": createAction("RECIPES/OPEN_EDIT_FORM"),

  "RECIPES/EDIT_RECIPE": createAction("RECIPES/EDIT_RECIPE"),
  "RECIPES/RESET_EDIT": createAction("RECIPES/RESET_EDIT"),

  "RECIPES/FETCH_RECIPE_DATA": createAction("RECIPES/FETCH_RECIPE_DATA"),
  "RECIPES/FETCH_RECIPE_DATA_SUCCESSFULLY": createAction("RECIPES/FETCH_RECIPE_DATA_SUCCESSFULLY"),
  "RECIPES/FETCH_RECIPE_DATA_ERROR": createAction("RECIPES/FETCH_RECIPE_DATA_ERROR"),
};